#!/bin/bash

FILE=$(cat /etc/motd.tail | grep -v "Note: Your MySQL password is in /etc/password.txt (delete this with \"erase_password_note\")" | head -n -2)

echo -e "$FILE" > /etc/motd.tail
rm /password.txt

echo -e "File /password.txt is removed.\n"
echo -e "The note is removed from /etc/motd after a reboot.\n"
