#!/bin/bash

if [ -f "/etc/motd.tail" ]; then
  FILE=$(cat /etc/motd.tail | grep -v "Note: Your MySQL password is in /etc/password.txt (delete this with \"erase_password_note\")" | head -n -2)
  echo -e "$FILE" > /etc/motd.tail
fi

if [ -f "/etc/update-motd.d/99-hetzner-lamp" ]; then
  rm "/etc/update-motd.d/99-hetzner-lamp"
fi

rm /password.txt

echo "File /password.txt is removed."
echo ""
echo "The note is removed from /etc/motd after a reboot."
echo ""
